{{- if and  (not .Values.useDaemonset)  .Values.autoscaling.hpa.enabled  }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: fluent-bit
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.autoscaling.hpa.behavior }}
  behavior:
    {{- toYaml .Values.autoscaling.hpa.behavior | nindent 4 }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "fluentBit.fullname" . }}
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  metrics:
  {{- if .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscaling.hpa.targetCPUUtilizationPercentage }}
          type: Utilization
  {{- end }}
  {{- if .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscaling.hpa.targetMemoryUtilizationPercentage }}
          type: Utilization
  {{- end }}
  {{- if .Values.autoscaling.hpa.customRules -}}
    {{- toYaml .Values.autoscaling.hpa.customRules | nindent 4}}
  {{- end -}}
{{- end }}
